// Color Wash - smooth ambient hue gradient for ENTTEC ELM
//
// ELM Parameters:
//   Force    (1-10) = Starting hue (maps across full color wheel)
//   Force 2  (1-10) = Hue spread (how much color varies across surface)
//   Nb Items (1-64) = Spatial waviness (1 = smooth gradient, higher = more undulation)
//   Speed           = Drift speed (built-in ELM control)

vec3 hsv2rgb(float h, float s, float v) {
    vec3 c = vec3(h, s, v);
    vec3 rgb = clamp(abs(mod(c.x * 6.0 + vec3(0.0, 4.0, 2.0), 6.0) - 3.0) - 1.0, 0.0, 1.0);
    return c.z * mix(vec3(1.0), rgb, c.y);
}



// >>> safe-color (generated by scripts/build-shaders.cjs) >>>
const float SAFE_SMIN = 0.4500;
const float SAFE_VMAX = 0.6000;
const float SAFE_EPS  = 0.0400;
vec3 safeHsv2rgb_(float h, float s, float v) {
    vec3 c = vec3(h, s, v);
    vec3 rgb = clamp(abs(mod(c.x * 6.0 + vec3(0.0, 4.0, 2.0), 6.0) - 3.0) - 1.0, 0.0, 1.0);
    return c.z * mix(vec3(1.0), rgb, c.y);
}
vec3 safeRgb2hsv_(vec3 c) {
    vec4 K = vec4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);
    vec4 p = mix(vec4(c.bg, K.wz), vec4(c.gb, K.xy), step(c.b, c.g));
    vec4 q = mix(vec4(p.xyw, c.r), vec4(c.r, p.yzx), step(p.x, c.r));
    float d = q.x - min(q.w, q.y);
    float e = 1.0e-10;
    return vec3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);
}
vec3 safeColor(vec3 rgb) {
    vec3 hsv = safeRgb2hsv_(rgb);
    float s = hsv.y, v = hsv.z;
    if (s < SAFE_SMIN && v > SAFE_VMAX) {
        if (s < SAFE_EPS) v = SAFE_VMAX;
        else if (SAFE_SMIN - s <= v - SAFE_VMAX) s = SAFE_SMIN;
        else v = SAFE_VMAX;
        return safeHsv2rgb_(hsv.x, s, v);
    }
    return rgb;
}
// <<< safe-color <<<

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;

    // Starting hue from Force (1-10 mapped to 0-1)
    float baseHue = (iForce - 1.0) / 9.0;

    // Hue spread from Force 2 (1-10 mapped to 0-0.5 of the wheel)
    float spread = (iForce2 - 1.0) / 9.0 * 0.5;

    // Waviness from Nb Items (+0.0 converts int to float)
    float wave = max(iNbItems + 0.0, 1.0);

    // Slow drift
    float t = iTime * 0.08;

    // Base diagonal gradient
    float grad = (uv.x + uv.y) * 0.5;

    // Add gentle sine modulation for spatial variation
    float wobble = 0.0;
    if (wave > 1.5) {
        float w = wave * 0.15;
        wobble += sin(uv.x * w * 6.0 + t * 2.0) * 0.12;
        wobble += sin(uv.y * w * 5.0 - t * 1.5) * 0.10;
        wobble += sin((uv.x - uv.y) * w * 3.0 + t) * 0.08;
    }

    // Final hue: base + spread across surface + wobble + slow time drift
    float hue = fract(baseHue + grad * spread + wobble + t);

    // Full saturation, full brightness
    vec3 col = hsv2rgb(hue, 1.0, 1.0);
    fragColor = vec4(safeColor(col), 1.0);
}
