// Uniform Test - experiment to discover which ELM uniforms work
//
// CONFIRMED WORKING:
//   iTime, iResolution, iForce (1-10), iForce2 (1-10), iNbItems (1-64)
//
// TESTING (may or may not be passed by ELM):
//   iZoom, iRotate, iSpeedFx, iCount
//
// After loading into ELM, check GET /elm/media/slots/{id}/parameters
// to see which parameters appear. The visual output encodes which
// uniforms are receiving non-zero values.

vec3 hsv2rgb(float h, float s, float v) {
    vec3 c = vec3(h, s, v);
    vec3 rgb = clamp(abs(mod(c.x * 6.0 + vec3(0.0, 4.0, 2.0), 6.0) - 3.0) - 1.0, 0.0, 1.0);
    return c.z * mix(vec3(1.0), rgb, c.y);
}



// >>> safe-color (generated by scripts/build-shaders.cjs) >>>
const float SAFE_SMIN = 0.4500;
const float SAFE_VMAX = 0.6000;
const float SAFE_EPS  = 0.0400;
vec3 safeHsv2rgb_(float h, float s, float v) {
    vec3 c = vec3(h, s, v);
    vec3 rgb = clamp(abs(mod(c.x * 6.0 + vec3(0.0, 4.0, 2.0), 6.0) - 3.0) - 1.0, 0.0, 1.0);
    return c.z * mix(vec3(1.0), rgb, c.y);
}
vec3 safeRgb2hsv_(vec3 c) {
    vec4 K = vec4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);
    vec4 p = mix(vec4(c.bg, K.wz), vec4(c.gb, K.xy), step(c.b, c.g));
    vec4 q = mix(vec4(p.xyw, c.r), vec4(c.r, p.yzx), step(p.x, c.r));
    float d = q.x - min(q.w, q.y);
    float e = 1.0e-10;
    return vec3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);
}
vec3 safeColor(vec3 rgb) {
    vec3 hsv = safeRgb2hsv_(rgb);
    float s = hsv.y, v = hsv.z;
    if (s < SAFE_SMIN && v > SAFE_VMAX) {
        if (s < SAFE_EPS) v = SAFE_VMAX;
        else if (SAFE_SMIN - s <= v - SAFE_VMAX) s = SAFE_SMIN;
        else v = SAFE_VMAX;
        return safeHsv2rgb_(hsv.x, s, v);
    }
    return rgb;
}
// <<< safe-color <<<

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;

    // Confirmed uniforms - left half of screen
    float hue1 = (iForce - 1.0) / 9.0;
    float hue2 = (iForce2 - 1.0) / 9.0;
    float tiles = max(iNbItems + 0.0, 1.0);
    float t = fract(uv.y * tiles - iTime * 0.2);

    vec3 confirmed = mix(hsv2rgb(hue1, 1.0, 1.0), hsv2rgb(hue2, 1.0, 1.0), t);

    // Experimental uniforms - right half shows diagnostic bars
    // Each bar lights up if the uniform has a non-zero value
    float barH = 0.2;
    vec3 testColor = vec3(0.0);

    // Bar 1 (bottom): iZoom
    if (uv.y < barH) {
        testColor = vec3(0.0, iZoom * 0.5, 0.0);
    }
    // Bar 2: iRotate
    else if (uv.y < barH * 2.0) {
        testColor = vec3(iRotate / 360.0, 0.0, 0.0);
    }
    // Bar 3: iSpeedFx
    else if (uv.y < barH * 3.0) {
        testColor = vec3(0.0, 0.0, iSpeedFx * 0.5);
    }
    // Bar 4: iCount
    else if (uv.y < barH * 4.0) {
        testColor = vec3(iCount / 64.0, iCount / 64.0, 0.0);
    }
    // Bar 5 (top): confirmed iForce for reference
    else {
        testColor = hsv2rgb(hue1, 1.0, 1.0);
    }

    // Left half = confirmed gradient, right half = test bars
    vec3 col = uv.x < 0.5 ? confirmed : testColor;
    fragColor = vec4(safeColor(col), 1.0);
}
