/**
 * Inject the glitch-zone clamp into every shaders/*.frag so ELM-generated
 * shader output can never land in the forbidden HSV corner.
 *
 * Thresholds are read from safe-color.json (written by the /calibrate tool),
 * so re-run this after calibrating:  node scripts/build-shaders.cjs
 *
 * Idempotent: a marked block is stripped and re-injected each run, and the
 * final output wrap is reverted before being re-applied.
 *
 * IMPORTANT: editing the .frag here does NOT update ELM — re-import the patched
 * files into the ELM project (LOOP-V2-ALL-HALFED.elm) and save it.
 */

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const zone = JSON.parse(fs.readFileSync(path.join(root, 'safe-color.json'), 'utf-8'));
const sMin = Number(zone.sMin);
const vMax = Number(zone.vMax);
const eps = Number(zone.achromaticEps ?? 0.04);

const BEGIN = '// >>> safe-color (generated by scripts/build-shaders.cjs) >>>';
const END = '// <<< safe-color <<<';

function block() {
  return `${BEGIN}
const float SAFE_SMIN = ${sMin.toFixed(4)};
const float SAFE_VMAX = ${vMax.toFixed(4)};
const float SAFE_EPS  = ${eps.toFixed(4)};
vec3 safeHsv2rgb_(float h, float s, float v) {
    vec3 c = vec3(h, s, v);
    vec3 rgb = clamp(abs(mod(c.x * 6.0 + vec3(0.0, 4.0, 2.0), 6.0) - 3.0) - 1.0, 0.0, 1.0);
    return c.z * mix(vec3(1.0), rgb, c.y);
}
vec3 safeRgb2hsv_(vec3 c) {
    vec4 K = vec4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);
    vec4 p = mix(vec4(c.bg, K.wz), vec4(c.gb, K.xy), step(c.b, c.g));
    vec4 q = mix(vec4(p.xyw, c.r), vec4(c.r, p.yzx), step(p.x, c.r));
    float d = q.x - min(q.w, q.y);
    float e = 1.0e-10;
    return vec3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);
}
vec3 safeColor(vec3 rgb) {
    vec3 hsv = safeRgb2hsv_(rgb);
    float s = hsv.y, v = hsv.z;
    if (s < SAFE_SMIN && v > SAFE_VMAX) {
        if (s < SAFE_EPS) v = SAFE_VMAX;
        else if (SAFE_SMIN - s <= v - SAFE_VMAX) s = SAFE_SMIN;
        else v = SAFE_VMAX;
        return safeHsv2rgb_(hsv.x, s, v);
    }
    return rgb;
}
${END}`;
}

const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const STRIP_RE = new RegExp(esc(BEGIN) + '[\\s\\S]*?' + esc(END) + '\\n?', 'g');

const dir = path.join(root, 'shaders');
const files = fs.readdirSync(dir).filter(f => f.endsWith('.frag'));
let changed = 0;

for (const f of files) {
  const p = path.join(dir, f);
  let src = fs.readFileSync(p, 'utf-8');
  const before = src;

  src = src.replace(STRIP_RE, '');                                       // strip old block
  src = src.replace('fragColor = vec4(safeColor(col), 1.0)', 'fragColor = vec4(col, 1.0)'); // revert wrap

  if (!src.includes('void mainImage')) {
    console.warn(`  [skip] ${f}: no "void mainImage" entrypoint`);
    continue;
  }
  src = src.replace('void mainImage', block() + '\n\nvoid mainImage');   // inject
  src = src.replace('fragColor = vec4(col, 1.0)', 'fragColor = vec4(safeColor(col), 1.0)'); // wrap output

  if (src !== before) { fs.writeFileSync(p, src, 'utf-8'); changed++; }
}

console.log(`safe-color injected into ${changed}/${files.length} shaders (sMin=${sMin}, vMax=${vMax}, eps=${eps}).`);
console.log('Re-import the patched .frag files into the ELM project for them to take effect at the fixtures.');
